config/routes.rb
Rails.application.routes.draw do

  namespace :spud do
    namespace :admin do
      resources :posts do
      	resources :post_comments, :path => 'comments', :only => :index
      end
      resources :news_posts
      resources :post_comments, :except => [:new, :create, :edit, :update] do
        member do
          get 'approve'
          get 'spam'
        end
      end
      resources :post_categories
    end
    namespace :blog do
      resource :sitemap,:only => "show"
    end
  end

  if Spud::Blog.config.blog_enabled
    scope (Spud::Blog.config.blog_path == '/' ? 'blog' : Spud::Blog.config.blog_path) do

      # Blog Post Categories
      get 'category/:category_url_name(/page/:page)',
        :controller => 'blog',
        :action => 'category',
        :as => 'blog_category',
        :defaults => {:page => 1}
      get 'category/:category_url_name/:archive_date(/page/:page)',
        :controller => 'blog',
        :action => 'category',
        :as => 'blog_category_archive',
        :defaults => {:page => 1}

      # Blog Post Archives
      get 'archive/:archive_date(/page/:page)',
        :controller => 'blog',
        :action => 'archive',
        :as => 'blog_archive',
        :defaults => {:page => 1}

      # Category/Archive filtering
      post '/', :controller => 'blog', :action => 'filter'

      # Blog Posts
      get '/(page/:page)',
        :controller => 'blog',
        :action => 'index',
        :as => 'blog',
        :defaults => {:page => 1}
      resources :blog_posts, :path => '/', :controller => 'blog', :only => [:show] do
        post '/', :on => :member, :controller => 'blog', :action => 'create_comment'
      end
    end
  end

  if Spud::Blog.config.news_enabled
    scope (Spud::Blog.config.news_path == '/' ? 'news' : Spud::Blog.config.news_path) do

      # News Post Categories
      get 'category/:category_url_name(/page/:page)',
        :controller => 'news',
        :action => 'category',
        :as => 'news_category',
        :defaults => {:page => 1}
      get 'category/:category_url_name/:archive_date(/page/:page)',
        :controller => 'news',
        :action => 'category',
        :as => 'news_category_archive',
        :defaults => {:page => 1}

      # News Post Archives
      get 'archive/:archive_date(/page/:page)',
        :controller => 'news',
        :action => 'archive',
        :as => 'news_archive',
        :defaults => {:page => 1}

      # Category/Archive filtering
      post '/', :controller => 'news', :action => 'filter'

      # News Posts
      get '/(page/:page)',
        :controller => 'news',
        :action => 'index',
        :as => 'news',
        :defaults => {:page => 1}
      resources :news_posts, :path => '/', :controller => 'news', :only => [:show]
    end
  end

  if Spud::Blog.config.blog_path == '/'
    root 'blog#index'
  elsif Spud::Blog.config.news_path == '/'
    root 'news#index'
  end
end

app/models/spud_post.rb
class SpudPost < ActiveRecord::Base
	spud_searchable

	has_and_belongs_to_many :categories,
		:class_name => 'SpudPostCategory',
		:join_table => 'spud_post_categories_posts',
		:foreign_key => 'spud_post_id'
	belongs_to :author, :class_name => 'SpudUser', :foreign_key => 'spud_user_id'
	has_many :comments, :class_name => 'SpudPostComment'
	has_many :visible_comments, -> { where spam: [nil,false]}, :class_name => 'SpudPostComment'
	has_many :spam_comments, -> { where spam: true }, :class_name => "SpudPostComment"
	has_many :spud_permalinks,:as => :attachment
	has_many :spud_post_sites, :dependent => :destroy

	scope :publicly, -> { where('visible = true AND published_at <= ?', Time.now.utc).order('published_at desc') }
	scope :future_posts, -> { where('visible = true AND published_at > ?', Time.now.utc) }
	validates_presence_of :title, :content, :published_at, :spud_user_id, :url_name
	validates_uniqueness_of :url_name
	before_validation :set_url_name
	before_save :postprocess_content

	after_save :set_spud_site_ids

	attr_accessor :spud_site_ids

	def self.for_spud_site(spud_site_id)
		return joins(:spud_post_sites).where(:spud_post_sites => {:spud_site_id => spud_site_id})
	end

	def self.public_posts(page, per_page)
		return where('visible = ? AND published_at <= ?', true,Time.now.utc).order('published_at desc').includes(:categories).paginate(:page => page, :per_page => per_page)
	end

	def self.public_blog_posts(page, per_page)
		return self.public_posts(page, per_page).where(:is_news => false)
	end

	def self.public_news_posts(page, per_page)
		return self.public_posts(page, per_page).where(:is_news => true)
	end

	def self.recent_posts(limit=5)
		return where('visible = ? AND published_at <= ?', true, Time.now.utc).order('published_at desc').limit(limit)
	end

	def self.recent_blog_posts(limit=5)
		return self.recent_posts(limit).where(:is_news => false)
	end

	def self.recent_news_posts(limit=5)
		return self.recent_posts(limit).where(:is_news => true)
	end

	def self.from_archive(date_string)
		begin
			date = Date.strptime(date_string, "%Y-%b")
			return where(:published_at => date..date.end_of_month)
		rescue
			return all
		end
	end

	#def self.posts_for_category_archive(category, )

 	# Returns an array of Date objects for months with public posts
	def self.months_with_public_posts
		# Select
		# 	Month(published_at) as published_month,
		# 	Year(published_at) as published_year
		# From spud_posts
		# Where visible = 1
		# And published_at < '2012-01-30'
		# Group By published_month, published_year
		# Order By published_year desc, published_month desc
		records = SpudPost.select('Extract(Month from published_at) as published_month, Extract(Year from published_at) as published_year').where('visible = ? AND published_at < ?', true, DateTime.now).group('published_month, published_year').order('published_year desc, published_month desc')
		begin
			return records.collect{ |r| Date.new(r[:published_year].to_i, r[:published_month].to_i) }
		rescue Exception => e
			logger.fatal "Exception occurred while fetching post archive dates:\n #{e.to_s}"
			return []
		end
	end

	def self.months_with_public_news_posts
		records = SpudPost.select('Extract(Month from published_at) as published_month, Extract(Year from published_at) as published_year').where('visible = ? AND published_at < ? AND is_news = ?', true, DateTime.now, true).group('published_month, published_year').order('published_year desc, published_month desc')
		begin
			return records.collect{ |r| Date.new(r[:published_year].to_i, r[:published_month].to_i) }
		rescue Exception => e
			logger.fatal "Exception occurred while fetching post archive dates:\n #{e.to_s}"
		end
	end

	def self.months_with_public_blog_posts
		records = SpudPost.select('Extract(Month from published_at) as published_month, Extract(Year from published_at) as published_year').where('visible = ? AND published_at < ? AND is_news = ?', true, DateTime.now, false).group('published_month, published_year').order('published_year desc, published_month desc')
		begin
			return records.collect{ |r| Date.new(r[:published_year].to_i, r[:published_month].to_i) }
		rescue Exception => e
			logger.fatal "Exception occurred while fetching post archive dates:\n #{e.to_s}"
		end
	end

	def postprocess_content
		rendererClass = Spud::Core.renderer(self.content_format)
		if rendererClass
			renderer = rendererClass.new()
			self.content_processed = renderer.render self.content
		else
			self.content_processed = content
		end
	end

	def content_processed
		if read_attribute(:content_processed).blank?
			postprocess_content
		end
		read_attribute(:content_processed)
	end

	def content_processed=(content)
		write_attribute(:content_processed,content)
	end

	def display_date
		return published_at.strftime("%b %d, %Y")
	end

	def is_public?
		return (published_at < DateTime.now) && visible
	end

	def is_private?
		return !is_public?
	end

	# Spud site ids getter
	def spud_site_ids
		if @spud_site_ids.nil?
			@spud_site_ids = spud_post_sites.collect{ |site| site.spud_site_id }
		end
		return @spud_site_ids
	end

	# Spud site ids setter
	def spud_site_ids=(site_ids)
		if site_ids.is_a?(Array)
			@spud_site_ids = site_ids.collect{ |id| id.to_i }
		else
			raise 'Site ids must be an Array'
		end
	end

	private

	def set_url_name
		self.url_name = "#{self.published_at.strftime('%Y-%m-%d')}-#{self.title.parameterize}"
	end

	def set_spud_site_ids
		if Spud::Core.multisite_mode_enabled
			_spud_post_sites = []
			self.spud_site_ids.each do |site_id|
				_spud_post_sites << SpudPostSite.new(:spud_post_id => id, :spud_site_id => site_id)
			end
			self.spud_post_sites = _spud_post_sites
		end
	end
end

app/controllers/spud/admin/posts_controller.rb
class Spud::Admin::PostsController < Spud::Admin::ApplicationController

	layout 'spud/admin/detail'
	respond_to :html, :xml, :json
	before_filter :find_post, :only => [:show, :edit, :update, :destroy]
	add_breadcrumb 'Blog Posts', :spud_admin_posts_path
	belongs_to_spud_app :blog_posts

	def index
		@posts = SpudPost.where(:is_news => false).order('published_at desc').includes(:visible_comments, :spam_comments, :author).paginate(:page => params[:page], :per_page => 15)
		respond_with @posts
	end

	def edit
		@categories = SpudPostCategory.grouped
		respond_with @post
	end

	def update
		@categories = SpudPostCategory.grouped
		params[:spud_post][:spud_site_ids] ||= []
		if @post.update_attributes(post_params)
			flash[:notice] = 'Post was successfully updated.'
		end
    respond_with @post, :location => spud_admin_posts_path
	end

	def new
		@categories = SpudPostCategory.grouped
		@post = SpudPost.new(:published_at => Time.zone.now, :spud_user_id => current_user.id, :spud_site_ids => [session[:admin_site] || 0])
		respond_with @post
	end

	def create
		@categories = SpudPostCategory.grouped
		params[:spud_post][:spud_site_ids] ||= []
		@post = SpudPost.new(post_params)
		if @post.save
	    flash[:notice] = 'Post was successfully created.'
		end
    respond_with @post, :location => spud_admin_posts_path
	end

	def destroy
		if @post.destroy
	    flash[:notice] = 'Post was successfully deleted.'
		end
    respond_with @post, :location => spud_admin_posts_path
	end

private

	def find_post
		@post = SpudPost.find(params[:id])
		if @post.blank?
			flash[:error] = "Post not found!"
			redirect_to spud_admin_posts_path and return false
		end
	end


	def post_params
		allowed_params = [:is_news,:published_at,:title,:content,:spud_user_id,:url_name,:visible,:comments_enabled,:meta_keywords,:meta_description,{:category_ids => []}, {:spud_site_ids => []}, :content_format]
		if Spud::Blog.config.custom_fields
			allowed_params.concat(Spud::Blog.config.custom_fields)
		end
		params.require(:spud_post).permit *allowed_params
	end

end

app/helpers/spud/admin/posts_helper.rb
module Spud::Admin::PostsHelper

	def options_for_parent_category(parent_id = 0)
		if @categories[parent_id]
			return @categories[parent_id].collect{ |c| 
				opts = [c.name, c.id] 
				opts += options_for_parent_category(c.id)
			}
		else
			return []
		end
	end

	def spud_post_site_check_box_tag(site, post)
		return check_box_tag 'spud_post[spud_site_ids][]', site[:site_id], post.spud_site_ids.include?(site[:site_id]), :id => "spud_post_site_id_#{site[:site_id]}"
	end

	def spud_post_site_label_tag(site)
		return label_tag "spud_post_site_id_#{site[:site_id]}", site[:site_name], :class => 'checkbox inline'
	end

end

app/views/spud/admin/posts/_category.html.erb
<%= content_tag :li, :class => 'spud_post_form_category', 'data-id' => category.id do %>
	<%= check_box_tag 'spud_post[category_ids][]', category.id, @post.category_ids.include?(category.id), :id => "spud_post_category_#{category.id}" %>
	<%= label_tag "spud_post_category_#{category.id}", category.name %>
  <ul>
    <% if @categories[category.id] %>
      <%= render :partial => '/spud/admin/posts/category', :collection => @categories[category.id] %>
  	<% end %>
  </ul>
<% end %>

app/views/spud/admin/posts/_form.html.erb
<%=error_messages_for(f.object)%>

<fieldset>
	<div class="form-group">
		<%= f.label :title, :required=>true,:style =>"display:none;" %>
		<div class="col-sm-12">
			<%= f.text_field :title, :class => "full-width form-control",:placeholder=>"Enter title here" %>		
		</div>
	</div>
</fieldset>
	
<div class="formtab clearfix">
	<div class="form-group">
		<div class="col-sm-12">
			<%=f.select :content_format,Spud::Core.renderers.collect { |k,v| [v[:description] || k, k]}, {:include_blank => false}, :class => "pull-right", "data-formatter" => "spud_post_content"%>
		</div>
	</div>
	<%= f.text_area :content,:style => "width:100%;", :class => 'spud-formatted-editor full-width', "data-format" => f.object.content_format %>
</div>

<% if Spud::Blog.config.has_custom_fields %>
<fieldset>
	<legend>Custom Fields</legend>
	<%= render :partial => '/spud/admin/posts/custom_fields', :locals => {:f => f} %>
</fieldset>
<% end %>

<fieldset class="spud_post_form_fieldset">
	<legend>Advanced</legend>

		<div class="col-sm-6">
			<div class="form-horizontal">
			<h4>Meta Data</h4>

			<div class="form-group">
				<%= f.label :published_at, 'Publish Date', :class => "control-label col-sm-4" %>
				<div class="col-sm-8">
					<%= f.text_field :published_at,:value => f.object.published_at.strftime("%Y-%m-%d %H:%M") , :class => 'spud_form_date_picker form-control' %>
					<span class="time_select">
						<%= f.time_select :published_at, :ignore_date => true,:ampm => true%>
					</span>	
				</div>
				
			</div>

			<% if @current_user.super_admin %>
				<div class="form-group">
					<%= f.label :spud_user_id, 'Author', :class => "control-label col-sm-4" %>
					<div class="col-sm-8">
						<%= f.select :spud_user_id,options_for_select(SpudUser.order(:first_name,:last_name,:login).all.collect{|user| [user.full_name,user.id]},f.object.spud_user_id), :class => "form-control"%>	
					</div>
					
				</div>
			<% else %>
				<%= f.hidden_field :spud_user_id %>
			<% end %>

			<% if Spud::Core.config.multisite_mode_enabled %>
				<div class="form-group">
					<%= f.label :sites, 'Websites to Publish', :class => "control-label col-sm-4" %>
					<div class="spud_post_form_input_group col-sm-8">
						<%= spud_post_site_check_box_tag(Spud::Core.default_site_config, @post) %>
						<%= spud_post_site_label_tag(Spud::Core.default_site_config) %>
						<% Spud::Core.config.multisite_config.each do |site| %>
							<%= spud_post_site_check_box_tag(site, @post) %>
							<%= spud_post_site_label_tag(site) %>
						<% end %>
					</div>
				</div>
			<% end %>

			<div class="form-group">
				<%= f.label :visible, :class => "control-label col-sm-4" %>
				<div class="col-sm-8">
					<label class="radio-inline">
						<%= f.radio_button :visible, true %> Yes
					</label>
					<label class="radio-inline">
						<%= f.radio_button :visible, false %> No	
					</label>
				</div>
			</div>

			<% unless @post.is_news %>
				<div class="form-group">
					<%= f.label :comments_enabled,"Comments Enabled", :class => "control-label col-sm-4" %>
					<div class="col-sm-8">
						<label class="radio-inline">
							<%= f.radio_button :comments_enabled, true %> Yes
						</label>
						<label class="radio-inline">
							<%= f.radio_button :comments_enabled, false %> No	
						</label>
					</div>
				</div>
			<% end %>

			<div class="form-group">
				<%= f.label :meta_keywords, 'Keywords', :class => "control-label col-sm-4" %>
				<div class="col-sm-8">
					<%= f.text_field :meta_keywords, :class => "form-control" %>
					<span class="spud_post_form_help_block">A Comma seperated list of keywords for search engines. Keep it short (no more than 10 keywords)</span>	
				</div>
				
			</div>

			<div class="form-group">
				<%= f.label :meta_description, 'Description', :class => "control-label col-sm-4" %>
				<div class="col-sm-8">
					<%= f.text_area :meta_description, :class => "form-control" %>
					<span class="spud_post_form_help_block">A short description of the article. This is what appears on a search engines search result page.</span>	
				</div>
			</div>
		</div>
	</div>
	<div class="col-sm-6">
		<h4>Categories</h4>
		<%= link_to 'Add Category', new_spud_admin_post_category_path, :class => 'btn btn-sm btn-success spud_post_add_category' %>
		<input type="hidden" name="spud_post[category_ids][]" value="" />
		<ul class="spud_post_categories_form">
			<%= render :partial => '/spud/admin/posts/category', :collection => @categories[nil] %>
		</ul>
	</div>

</fieldset>
<%= f.hidden_field :is_news %>

<div class="col-sm-6 col-sm-offset-2">
	<%=f.submit "Save Post", :class=>"btn btn-primary form-btn","data-loading-text"=>"Saving..."%> or <%=link_to "cancel",request.referer, :class => "btn btn-default"%>
</div>

<script type="text/javascript">
	$(document).ready(spud.admin.posts.edit);
</script>

app/views/spud/admin/posts/edit.html.erb
<%= form_for @post, :url => spud_core.admin_post_path(@post), :html => {:class => 'form-horizontal'} do |f| %>
	<%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

app/views/spud/admin/posts/index.html.erb
<%= content_for :data_controls do %>
	<%= link_to "Manage Categories", spud_admin_post_categories_path, :class => 'btn btn-info spud_blog_manage_categories', :title => 'Manage Categories' %>
	<%= link_to "Manage Comments", spud_admin_post_comments_path, :class => 'btn btn-default', :title => 'Manage Comments' %>
	<%= link_to "New Post", new_spud_admin_post_path, :class => "btn btn-primary", :title => "New Post" %>
<% end %>

<%=content_for :detail do %>
	<table class="admin-table">
		<thead>
			<tr>
				<th>Title</th>
				<th>Author</th>
				<th>Published At</th>
				<th>Comments</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<% @posts.each do |post| %>
				<tr>
					<td>
						<%= link_to edit_spud_admin_post_path(post) do %>
							<%=post.title%>
							<%if !post.visible%>
								<span class="badge">Draft</span>
							<%end%>
						<%end%>
					</td>
					<td><%= post.author.try(:full_name) %></td>
					<td><%= link_to(post.published_at.strftime('%m/%d/%Y'), blog_post_path(post.url_name)) %></td>
					<td>
						Approved: <%=link_to post.visible_comments.count, spud_admin_post_post_comments_path(:post_id => post.id) %>
						<br/>
						Spam: <%=link_to post.spam_comments.count, spud_admin_post_post_comments_path(:post_id => post.id) %>
					</td>
					<td align="right">
						<%= link_to spud_admin_post_path(post), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this post?'}, :class => 'btn btn-sm btn-danger' do%>
							<span class="glyphicon glyphicon-trash"></span>
						<%end%>
					</td>
				</tr>
			<%end%>
		</tbody>
	</table>
	<div class="spud_admin_pagination">
		<%= will_paginate @posts %>
	</div>

	<script>
		$(document).ready(spud.admin.post_categories.index);
	</script>
<%end%>

app/views/spud/admin/posts/new.html.erb
<%= form_for @post, :url => spud_core.admin_posts_path do |f| %>
	<%= render :partial => 'form', :locals => {:f => f} %>
<% end %>