config/routes.rb
Rails.application.routes.draw do

  namespace :spud do
    namespace :admin do
      resources :posts do
      	resources :post_comments, :path => 'comments', :only => :index
      end
      resources :news_posts
      resources :post_comments, :except => [:new, :create, :edit, :update] do
        member do
          get 'approve'
          get 'spam'
        end
      end
      resources :post_categories
    end
    namespace :blog do
      resource :sitemap,:only => "show"
    end
  end

  if Spud::Blog.config.blog_enabled
    scope (Spud::Blog.config.blog_path == '/' ? 'blog' : Spud::Blog.config.blog_path) do

      # Blog Post Categories
      get 'category/:category_url_name(/page/:page)',
        :controller => 'blog',
        :action => 'category',
        :as => 'blog_category',
        :defaults => {:page => 1}
      get 'category/:category_url_name/:archive_date(/page/:page)',
        :controller => 'blog',
        :action => 'category',
        :as => 'blog_category_archive',
        :defaults => {:page => 1}

      # Blog Post Archives
      get 'archive/:archive_date(/page/:page)',
        :controller => 'blog',
        :action => 'archive',
        :as => 'blog_archive',
        :defaults => {:page => 1}

      # Category/Archive filtering
      post '/', :controller => 'blog', :action => 'filter'

      # Blog Posts
      get '/(page/:page)',
        :controller => 'blog',
        :action => 'index',
        :as => 'blog',
        :defaults => {:page => 1}
      resources :blog_posts, :path => '/', :controller => 'blog', :only => [:show] do
        post '/', :on => :member, :controller => 'blog', :action => 'create_comment'
      end
    end
  end

  if Spud::Blog.config.news_enabled
    scope (Spud::Blog.config.news_path == '/' ? 'news' : Spud::Blog.config.news_path) do

      # News Post Categories
      get 'category/:category_url_name(/page/:page)',
        :controller => 'news',
        :action => 'category',
        :as => 'news_category',
        :defaults => {:page => 1}
      get 'category/:category_url_name/:archive_date(/page/:page)',
        :controller => 'news',
        :action => 'category',
        :as => 'news_category_archive',
        :defaults => {:page => 1}

      # News Post Archives
      get 'archive/:archive_date(/page/:page)',
        :controller => 'news',
        :action => 'archive',
        :as => 'news_archive',
        :defaults => {:page => 1}

      # Category/Archive filtering
      post '/', :controller => 'news', :action => 'filter'

      # News Posts
      get '/(page/:page)',
        :controller => 'news',
        :action => 'index',
        :as => 'news',
        :defaults => {:page => 1}
      resources :news_posts, :path => '/', :controller => 'news', :only => [:show]
    end
  end

  if Spud::Blog.config.blog_path == '/'
    root 'blog#index'
  elsif Spud::Blog.config.news_path == '/'
    root 'news#index'
  end
end

app/controllers/spud/admin/post_categories_controller.rb
require 'actionpack/action_caching'
require 'actionpack/page_caching'

class Spud::Admin::PostCategoriesController < Spud::Admin::ApplicationController

	layout false
	respond_to :html, :json

	before_filter :find_category, :only => [:show, :edit, :update, :destroy]
	# cache_sweeper :spud_post_category_sweeper, :only => [:create, :update, :destroy]

	def index
		@post_categories = SpudPostCategory.grouped
		respond_with @post_categories
	end

	def edit
		respond_with @post_category
	end

	def update
		if @post_category.update_attributes(category_params)
			flash[:notice] = 'Post Category was successfully updated'
			respond_with @post_category, :location => spud_admin_post_categories_path
		else
			render 'new', :status => 422
		end
	end

	def new
		@post_category = SpudPostCategory.new
		respond_with @post_category
	end

	def create
		@post_category = SpudPostCategory.new(category_params)
		if @post_category.save
			flash[:notice] = 'Post Category was successfully created'
			respond_with @post_category, :location => spud_admin_post_categories_path
		else
			render 'new', :status => 422
		end
	end

	def destroy
		if @post_category.destroy
			flash[:notice] = 'Post Category was successfully deleted'
			@post_categories = SpudPostCategory.grouped
			render 'index'
		else
			respond_with @post_category, :location => spud_admin_post_categories_path
		end
	end

private

	def find_category
		@post_category = SpudPostCategory.find(params[:id])
	end

	def category_params
		params.require(:spud_post_category).permit(:name, :url_name, :parent_id)
	end
end

app/helpers/spud/admin/post_categories_helper.rb
module Spud::Admin::PostCategoriesHelper
end

app/views/spud/admin/post_categories/_category.html.erb
<%= content_tag :li, :class => 'spud_blog_category_manager_item', 'data-id' => category.id do %>
  <span class="spud_blog_category_manager_item_name">
    <%= category.name %>
  </span>
  <span class="spud_blog_category_manager_item_actions">
    <%= link_to edit_spud_admin_post_category_path(category), :class => 'btn btn-xs btn-link spud_blog_category_edit' do%>
      <span class="glyphicon glyphicon-pencil"></span>
    <%end%>
    <%= link_to spud_admin_post_category_path(category), :class => 'btn btn-xs btn-danger spud_blog_category_delete' do%>
      <span class="glyphicon glyphicon-trash"></span>
    <%end%>
  </span>
  <ul class="spud_blog_category_manager_item_children">
    <% if @post_categories[category.id] %>
      <%= render :partial => 'category', :collection => @post_categories[category.id] %>
    <% end %>
  </ul>
<% end %>

app/views/spud/admin/post_categories/_form.html.erb
<%= form_for @post_category, :url => (@post_category.new_record? ? spud_admin_post_categories_path : spud_admin_post_category_path(@post_category)), :html => {:class => 'form-horizontal spud_post_category_form'} do |f| %>

	<%= error_messages_for(f.object) %>

	<fieldset>
		<div class="form-group">
			<%= f.label :name,"Name",:class => "control-label col-sm-2" %>
			<div class="col-sm-10">
				<%= f.text_field :name, :class => "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= label_tag :parent,'Parent',:class => "control-label col-sm-2" %>
			<div class="col-sm-10">
				<select name="spud_post_category[parent_id]" class="form-control">
					<option value="">No Parent</option>
					<%= options_for_select(SpudPostCategory.options_for_categories(:filter => @post_category.id), @post_category.parent_id) %>
				</select>
			</div>
		</div>
	</fieldset>

<% end %>

app/views/spud/admin/post_categories/edit.html.erb
<%= render :partial => 'form' %>

app/views/spud/admin/post_categories/index.html.erb
<div class="spud_blog_category_manager">
	<%= link_to "New Post Category", new_spud_admin_post_category_path, :class => "btn btn-sm btn-success spud_blog_category_add_new", :title => "New Post Category" %>
	<ul class="spud_blog_category_manager_list">
    <% if @post_categories.length == 0 %>
      <li class="spud_blog_category_manager_empty">You do not have any Post Categories at this time.</li>
    <% end %> 
		<%= render :partial => 'category', :collection => @post_categories[nil] %>
	</ul>
</div>

app/views/spud/admin/post_categories/new.html.erb
<%= render :partial => 'form', :locals => {:path => spud_core.admin_post_categories_path} %>