config/routes.rb
Rails.application.routes.draw do

  namespace :spud do
    namespace :admin do
      resources :posts do
      	resources :post_comments, :path => 'comments', :only => :index
      end
      resources :news_posts
      resources :post_comments, :except => [:new, :create, :edit, :update] do
        member do
          get 'approve'
          get 'spam'
        end
      end
      resources :post_categories
    end
    namespace :blog do
      resource :sitemap,:only => "show"
    end
  end

  if Spud::Blog.config.blog_enabled
    scope (Spud::Blog.config.blog_path == '/' ? 'blog' : Spud::Blog.config.blog_path) do

      # Blog Post Categories
      get 'category/:category_url_name(/page/:page)',
        :controller => 'blog',
        :action => 'category',
        :as => 'blog_category',
        :defaults => {:page => 1}
      get 'category/:category_url_name/:archive_date(/page/:page)',
        :controller => 'blog',
        :action => 'category',
        :as => 'blog_category_archive',
        :defaults => {:page => 1}

      # Blog Post Archives
      get 'archive/:archive_date(/page/:page)',
        :controller => 'blog',
        :action => 'archive',
        :as => 'blog_archive',
        :defaults => {:page => 1}

      # Category/Archive filtering
      post '/', :controller => 'blog', :action => 'filter'

      # Blog Posts
      get '/(page/:page)',
        :controller => 'blog',
        :action => 'index',
        :as => 'blog',
        :defaults => {:page => 1}
      resources :blog_posts, :path => '/', :controller => 'blog', :only => [:show] do
        post '/', :on => :member, :controller => 'blog', :action => 'create_comment'
      end
    end
  end

  if Spud::Blog.config.news_enabled
    scope (Spud::Blog.config.news_path == '/' ? 'news' : Spud::Blog.config.news_path) do

      # News Post Categories
      get 'category/:category_url_name(/page/:page)',
        :controller => 'news',
        :action => 'category',
        :as => 'news_category',
        :defaults => {:page => 1}
      get 'category/:category_url_name/:archive_date(/page/:page)',
        :controller => 'news',
        :action => 'category',
        :as => 'news_category_archive',
        :defaults => {:page => 1}

      # News Post Archives
      get 'archive/:archive_date(/page/:page)',
        :controller => 'news',
        :action => 'archive',
        :as => 'news_archive',
        :defaults => {:page => 1}

      # Category/Archive filtering
      post '/', :controller => 'news', :action => 'filter'

      # News Posts
      get '/(page/:page)',
        :controller => 'news',
        :action => 'index',
        :as => 'news',
        :defaults => {:page => 1}
      resources :news_posts, :path => '/', :controller => 'news', :only => [:show]
    end
  end

  if Spud::Blog.config.blog_path == '/'
    root 'blog#index'
  elsif Spud::Blog.config.news_path == '/'
    root 'news#index'
  end
end

app/controllers/spud/admin/news_posts_controller.rb
class Spud::Admin::NewsPostsController < Spud::Admin::ApplicationController

	layout 'spud/admin/detail'
	respond_to :html, :xml, :json
	before_filter :find_post, :only => [:show, :edit, :update, :destroy]
	add_breadcrumb 'News Posts', :spud_admin_news_posts_path
	belongs_to_spud_app :news_posts

	def index
		@posts = SpudPost.where(:is_news => true).order('published_at desc').includes(:comments).paginate(:page => params[:page], :per_page => 15)
		respond_with @posts
	end

	def edit
		@categories = SpudPostCategory.grouped
		respond_with @post
	end

	def update
		@categories = SpudPostCategory.grouped
		params[:spud_post][:spud_site_ids] ||= []
		if @post.update_attributes(post_params)
	    flash[:notice] = 'News Post was successfully updated.'
		end
    respond_with @post, :location => spud_admin_news_posts_path
	end

	def new
		@categories = SpudPostCategory.grouped
		@post = SpudPost.new(:published_at => Time.zone.now, :spud_user_id => current_user.id, :is_news => true, :comments_enabled => false, :spud_site_ids => [current_site_id])
		respond_with @post
	end

	def create
		@categories = SpudPostCategory.grouped
		params[:spud_post][:spud_site_ids] ||= []
		@post = SpudPost.new(post_params)
		if @post.save
    	flash[:notice] = 'News Post was successfully created.'
		end
    respond_with @post, :location => spud_admin_news_posts_path
	end

	def destroy
		if @post.destroy
	    flash[:notice] = 'News Post was successfully deleted.'
		end
    respond_with @post, :location => spud_admin_news_posts_path
	end

	private

	def find_post
		@post = SpudPost.find(params[:id])
		if @post.blank?
			flash[:error] = 'News Post not found!'
			redirect_to spud_admin_news_posts_path and return false
		end
	end

	def post_params
		allowed_params = [:is_news,:published_at,:title,:content,:spud_user_id,:url_name,:visible,:comments_enabled,:meta_keywords,:meta_description,{:category_ids => []}, {:spud_site_ids => []}, :content_format]
		if Spud::Blog.config.custom_fields
			allowed_params.concat(Spud::Blog.config.custom_fields)
		end
		params.require(:spud_post).permit *allowed_params
	end

end

app/helpers/spud/admin/news_posts_helper.rb
module Spud::Admin::NewsPostsHelper
end

app/views/spud/admin/news_posts/edit.html.erb
<%= form_for @post, :url => spud_core.admin_news_post_path(@post), :html => {:class => 'form-horizontal'} do |f| %>
	<%= render :partial => '/spud/admin/posts/form', :locals => {:f => f} %>
<% end %>

app/views/spud/admin/news_posts/index.html.erb
<%= content_for :data_controls do %>
	<%= link_to "Manage Categories", spud_admin_post_categories_path, :class => 'btn spud_blog_manage_categories', :title => 'Manage Categories' %>
	<%= link_to "New Post", new_spud_admin_news_post_path, :class => "btn btn-primary", :title => "New Post" %>
<% end %>

<%=content_for :detail do %>
	<table class="admin-table">
		<thead>
			<tr>
				<th>Title</th>
				<th>Author</th>
				<th>Published At</th>
				<th>&nbsp;</th>
			</tr>			
		</thead>
		<tbody>
			<% @posts.each do |post| %>
				<tr>

					<td>
						<%= link_to edit_spud_admin_news_post_path(post) do %>
							<%=post.title%>
							<%if !post.visible%>
								<span class="badge">Draft</span>
							<%end%>
						<%end%>
					</td>
					<td><%= post.author.full_name %></td>
					<td><%= link_to(post.published_at.strftime('%m/%d/%Y'), news_post_path(post.url_name)) %></td>
					<td align="right">
						<%= link_to 'Delete', spud_admin_news_post_path(post), :method => :delete, :confirm => 'Are you sure you want to delete this post?', :class => 'btn btn-small btn-danger' %>
					</td>
				</tr>
			<%end%>
		</tbody>
	</table>
	<div class="spud_admin_pagination">
		<%= will_paginate @posts %>
	</div>

	<script>
		$(document).ready(spud.admin.post_categories.index);
	</script>
<%end%>

app/views/spud/admin/news_posts/new.html.erb
<%= form_for @post, :url => spud_core.admin_news_posts_path do |f| %>
	<%= render :partial => '/spud/admin/posts/form', :locals => {:f => f} %>
<% end %>