config/routes.rb
Rails.application.routes.draw do

  namespace :spud do
    namespace :admin do
      resources :posts do
      	resources :post_comments, :path => 'comments', :only => :index
      end
      resources :news_posts
      resources :post_comments, :except => [:new, :create, :edit, :update] do
        member do
          get 'approve'
          get 'spam'
        end
      end
      resources :post_categories
    end
    namespace :blog do
      resource :sitemap,:only => "show"
    end
  end

  if Spud::Blog.config.blog_enabled
    scope (Spud::Blog.config.blog_path == '/' ? 'blog' : Spud::Blog.config.blog_path) do

      # Blog Post Categories
      get 'category/:category_url_name(/page/:page)',
        :controller => 'blog',
        :action => 'category',
        :as => 'blog_category',
        :defaults => {:page => 1}
      get 'category/:category_url_name/:archive_date(/page/:page)',
        :controller => 'blog',
        :action => 'category',
        :as => 'blog_category_archive',
        :defaults => {:page => 1}

      # Blog Post Archives
      get 'archive/:archive_date(/page/:page)',
        :controller => 'blog',
        :action => 'archive',
        :as => 'blog_archive',
        :defaults => {:page => 1}

      # Category/Archive filtering
      post '/', :controller => 'blog', :action => 'filter'

      # Blog Posts
      get '/(page/:page)',
        :controller => 'blog',
        :action => 'index',
        :as => 'blog',
        :defaults => {:page => 1}
      resources :blog_posts, :path => '/', :controller => 'blog', :only => [:show] do
        post '/', :on => :member, :controller => 'blog', :action => 'create_comment'
      end
    end
  end

  if Spud::Blog.config.news_enabled
    scope (Spud::Blog.config.news_path == '/' ? 'news' : Spud::Blog.config.news_path) do

      # News Post Categories
      get 'category/:category_url_name(/page/:page)',
        :controller => 'news',
        :action => 'category',
        :as => 'news_category',
        :defaults => {:page => 1}
      get 'category/:category_url_name/:archive_date(/page/:page)',
        :controller => 'news',
        :action => 'category',
        :as => 'news_category_archive',
        :defaults => {:page => 1}

      # News Post Archives
      get 'archive/:archive_date(/page/:page)',
        :controller => 'news',
        :action => 'archive',
        :as => 'news_archive',
        :defaults => {:page => 1}

      # Category/Archive filtering
      post '/', :controller => 'news', :action => 'filter'

      # News Posts
      get '/(page/:page)',
        :controller => 'news',
        :action => 'index',
        :as => 'news',
        :defaults => {:page => 1}
      resources :news_posts, :path => '/', :controller => 'news', :only => [:show]
    end
  end

  if Spud::Blog.config.blog_path == '/'
    root 'blog#index'
  elsif Spud::Blog.config.news_path == '/'
    root 'news#index'
  end
end

app/controllers/spud/admin/post_comments_controller.rb
class Spud::Admin::PostCommentsController < Spud::Admin::ApplicationController

	respond_to :html, :xml, :json
	layout 'spud/admin/detail'
	belongs_to_spud_app :blog_posts
	before_filter :find_comment, :only => [:show, :edit, :update, :destroy, :approve, :spam]
	add_breadcrumb 'Blog Posts', :spud_admin_posts_path
	add_breadcrumb 'Comments', :spud_admin_post_comments_path


	def index
		@page_name = "Comments"
		if params[:post_id]
			@post_comments = SpudPost.find(params[:post_id]).comments
		else
			@post_comments = SpudPostComment
		end
		@post_comments = @post_comments.paginate :page => params[:page]
		respond_with @post_comments
	end

	def show
		respond_with @post_comment
	end

	def edit
		respond_with @post_comment
	end

	def update

	end

	def create

	end

	def approve

		if Spud::Blog.enable_rakismet && @post_comment.spam
			@post_comment.ham!
		end
		@post_comment.update_attributes(:spam => false)
		redirect_to request.referer || spud_admin_post_comments_path
	end

	def spam
		if Spud::Blog.enable_rakismet && !@post_comment.spam
			@post_comment.spam!
		end
		@post_comment.update_attributes(:spam => true)
		redirect_to request.referer || spud_admin_post_comments_path
	end

	def destroy
		if !@post_comment.destroy
			flash[:error] = "Whoops! Something odd happened while trying to delete that comment. Thats not fun. please try again."
		end
		respond_with @post_comment, :location => request.referer || spud_admin_post_comments_path
	end

	private

	def find_comment
		@post_comment = SpudPostComment.find(params[:id])
	end

end

app/helpers/spud/admin/post_comments_helper.rb
module Spud::Admin::PostCommentsHelper
end

app/views/spud/admin/post_comments/index.html.erb
<%= content_for :data_controls do %>

<% end %>

<%=content_for :detail do %>
  <table class="admin-table table table-responsive">
    <thead>
      <tr>

        <th>Author</th>
        <th>Comment</th>
        <th>Attached To</th>
        <th>Status</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @post_comments.each do |comment| %>
        <tr>
          <td><%= comment.author %></td>
          <td>
            <span class='submitted-on'>Submitted: <%=timestamp(comment.created_at)%></span>
            <%= comment.content %>
          </td>
          <td><%= link_to comment.post.title, blog_post_path(comment.post.url_name)%></td>
          <td>
            <% if comment.spam %>
              Spam
            <% else %>
              Approved
            <% end %>
          </td>
          <td align="right" style="min-width:200px;">
            <%= link_to 'Approve', approve_spud_admin_post_comment_path(comment), :class => 'btn btn-success btn-sm' %>
            <%= link_to 'Spam', spam_spud_admin_post_comment_path(comment), :class => 'btn btn-warning btn-sm' %>
            <%= link_to spud_admin_post_comment_path(comment), :method => :delete, :confirm => 'Are you sure you want to delete this comment?', :class => 'btn btn-danger btn-sm' do%>
              <span class="glyphicon glyphicon-trash"></span>
            <%end%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <div class="spud_admin_pagination">
    <%= will_paginate @post_comments%>
  </div>


<%end%>